### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by pel-daniel** [minimalistOrg/minimalisIdeV2#2]
# Roadmap

## Close/hide bubbles

- [ ] Close single bubble
- [ ] Close to the right
- [ ] Collapse bubble
- [ ] Collapse bubble lane

## Bubble lane options

- [ ] Wrap
- [ ] Reverse

## Settings

- [ ] Color themes/customize colors
- [ ] Programming language options
  - [ ] Show parenthesis
  - [ ] Show commas
  - [ ] Show braces/show `:` 
- [ ] Tab size
- [ ] Default bubble width/height

## View layouts

- [ ] MVC
- [ ] Test mode
